set(_CATKIN_CURRENT_PACKAGE "odometery")
set(odometery_VERSION "0.0.0")
set(odometery_MAINTAINER "nvidia <nvidia@todo.todo>")
set(odometery_PACKAGE_FORMAT "2")
set(odometery_BUILD_DEPENDS "geometry_msgs" "roscpp" "rospy" "tf")
set(odometery_BUILD_EXPORT_DEPENDS "geometry_msgs" "roscpp" "rospy" "tf")
set(odometery_BUILDTOOL_DEPENDS "catkin")
set(odometery_BUILDTOOL_EXPORT_DEPENDS )
set(odometery_EXEC_DEPENDS "geometry_msgs" "roscpp" "rospy" "tf")
set(odometery_RUN_DEPENDS "geometry_msgs" "roscpp" "rospy" "tf")
set(odometery_TEST_DEPENDS )
set(odometery_DOC_DEPENDS )
set(odometery_URL_WEBSITE "")
set(odometery_URL_BUGTRACKER "")
set(odometery_URL_REPOSITORY "")
set(odometery_DEPRECATED "")